name: raihan_cli
description: "raihan_cli generates clean Flutter feature folders with Clean Architecture principles, supporting MVC and MVVM patterns, and integrates seamlessly with GetX, Provider, Riverpod, and BLoC state management."
version: 2.0.1
homepage: https://github.com/raihansikdar/raihan_cli

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

executables:
  raihan_cli: raihan_cli

dependencies:
  flutter:
    sdk: flutter
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15